export const themes = {
  popart: {
    name: "🎨 Pop-Art",
    appBg: "bg-transparent selection:bg-[#FF0055] selection:text-white transition-colors duration-300",
    header: "bg-[#FFE600] border-b-4 border-black shadow-[0_8px_0_0_#000] p-4 sticky top-0 z-50",
    headerLogoBg: "bg-[#FF0055] border-4 border-black p-2 shadow-[4px_4px_0_0_#000] rotate-3 text-white",
    headerTitle: "text-2xl font-black uppercase tracking-tighter bg-white px-2 border-2 border-black inline-block transform -rotate-1 text-black",
    headerSubtitle: "text-[10px] font-black bg-[#00E5FF] text-black px-1 border-2 border-black inline-block uppercase mt-1",
    btnToggle: "bg-[#FF0055] text-white border-4 border-black px-3 py-2 text-xs font-black uppercase shadow-[4px_4px_0_0_#000] active:translate-x-1 active:translate-y-1 active:shadow-none transition-all",
    btnWallet: "bg-[#00E5FF] hover:bg-white text-black font-black border-4 border-black px-6 py-2 uppercase shadow-[6px_6px_0_0_#000] active:translate-x-1 active:translate-y-1 active:shadow-none transition-all text-sm",
    btnDisconnect: "bg-[#FF0055] text-white border-4 border-black px-3 py-2 text-xs font-black uppercase hover:bg-black hover:text-[#FF0055] shadow-[4px_4px_0_0_#000] active:translate-x-1 active:translate-y-1 active:shadow-none transition-all",
    walletBadge: "bg-[#00FF66] border-4 border-black px-4 py-2 font-black text-xs shadow-[4px_4px_0_0_#000] text-black",
    errorAlert: "bg-[#FF0055] text-white border-4 border-black p-4 font-black uppercase text-sm mb-6 shadow-[6px_6px_0_0_#000] animate-shake",
    
    tabActive: "bg-[#00FF66] text-black border-4 border-black font-black uppercase px-6 py-3 text-sm translate-x-1 translate-y-1",
    tabInactive: "bg-white hover:bg-[#00E5FF] text-black border-4 border-black font-black uppercase px-6 py-3 text-sm shadow-[4px_4px_0_0_#000] active:translate-x-1 active:translate-y-1 active:shadow-none transform hover:-translate-y-1 transition-all",
    
    // Panel Emisor
    panelHeader: "mb-8 bg-[#00E5FF] border-4 border-black p-4 shadow-[8px_8px_0_0_#FF0055] flex flex-col md:flex-row justify-between items-center transform -rotate-1 text-black",
    panelTitle: "text-3xl md:text-4xl font-black uppercase tracking-tighter bg-white px-2 border-2 border-black inline-block",
    panelSubtitle: "font-black text-[10px] mt-2 uppercase bg-black text-[#00E5FF] p-1 border-2 border-white inline-block",
    panelRole: "mt-4 md:mt-0 bg-[#FF0055] text-white px-4 py-2 font-black text-xs border-4 border-black shadow-[4px_4px_0_0_#000] rotate-2",
    
    cardMain: "bg-white border-4 border-black shadow-[12px_12px_0_0_#BF5AF2] p-6 md:p-8 text-black",
    dropZone: "mb-8 border-4 border-dashed border-black bg-[#FFE600] hover:bg-black hover:text-[#FFE600] transition-colors p-8 flex flex-col items-center justify-center cursor-pointer active:translate-y-1 shadow-[4px_4px_0_0_#000]",
    dropText: "font-black uppercase text-base bg-white text-black px-2 border-2 border-black mt-4 text-center",
    dropSubtext: "text-[10px] font-black mt-2 bg-black text-white px-2 py-1 text-center",
    
    inputWrapper: "relative",
    inputLabelHash: "absolute -top-3 left-4 bg-[#BF5AF2] text-white border-2 border-black px-2 text-[10px] font-black uppercase z-10",
    inputLabelNombre: "absolute -top-3 left-4 bg-[#FF0055] text-white border-2 border-black px-2 text-[10px] font-black uppercase z-10",
    inputLabelCarrera: "absolute -top-3 left-4 bg-[#00FF66] text-black border-2 border-black px-2 text-[10px] font-black uppercase z-10",
    inputLabelWallet: "absolute -top-3 left-4 bg-black text-[#FFE600] border-2 border-black px-2 text-[10px] font-black uppercase z-10",
    inputField: "w-full border-4 border-black p-4 pt-5 font-mono text-sm focus:outline-none focus:bg-[#00E5FF] transition-colors bg-neutral-50 shadow-[4px_4px_0_0_#000] text-black",
    
    btnSubmit: "w-full bg-[#00FF66] hover:bg-black hover:text-[#00FF66] text-black font-black uppercase text-xl p-5 border-4 border-black shadow-[8px_8px_0_0_#000] active:translate-x-2 active:translate-y-2 active:shadow-none transition-all mt-6 disabled:opacity-50 disabled:cursor-not-allowed",
    statusBox: "mt-8 p-4 border-4 border-black bg-black text-[#00E5FF] font-black text-sm uppercase shadow-[6px_6px_0_0_#FF0055] rotate-1",
    
    sidebarCard: "bg-[#BF5AF2] border-4 border-black shadow-[8px_8px_0_0_#000] p-6 h-fit text-white transform rotate-1",
    sidebarHeader: "text-lg font-black uppercase border-b-4 border-black pb-3 mb-6 bg-black p-2 -rotate-2",
    sidebarItem1: "flex items-center justify-between border-4 border-black p-3 bg-white text-black shadow-[4px_4px_0_0_#000]",
    sidebarItem1Label: "text-xs font-black uppercase",
    sidebarItem1Value: "text-xs font-black bg-black text-[#00FF66] px-1",
    sidebarItem2: "border-4 border-black p-3 bg-white text-black shadow-[4px_4px_0_0_#000]",
    sidebarItem2Label: "block text-[10px] font-black uppercase bg-black text-white px-1 inline-block mb-2",
    sidebarItem3: "border-4 border-black p-3 bg-[#FFE600] text-black shadow-[4px_4px_0_0_#000] transform -rotate-2",
    sidebarItem3Label: "block text-[10px] font-black uppercase bg-black text-[#FFE600] px-1 inline-block mb-2",
    sidebarItem3Value: "text-2xl font-black text-[#FF0055]",
    sidebarItem4: "border-4 border-black p-3 bg-[#00E5FF] text-black shadow-[4px_4px_0_0_#000]",
    sidebarItem4Label: "block text-[10px] font-black uppercase bg-black text-[#00E5FF] px-1 inline-block mb-2",
    
    // Portal Estudiante
    portalHeader: "mb-8 bg-[#FFE600] border-4 border-black p-4 shadow-[8px_8px_0_0_#000] flex flex-col md:flex-row justify-between md:items-center gap-4 text-black",
    portalTitle: "text-3xl font-black uppercase tracking-tight",
    portalSubtitle: "font-bold text-xs mt-1 uppercase",
    portalWallet: "bg-black text-[#FFE600] px-4 py-2 font-black text-xs border-2 border-black break-all",
    portalCol1: "bg-white border-4 border-black shadow-[8px_8px_0_0_#000] p-6 h-fit text-black",
    portalCol1Title: "text-lg font-black uppercase mb-4 border-b-4 border-black pb-2",
    portalCol1Text: "text-xs font-bold text-neutral-600 mb-4",
    portalInputLabel: "block text-xs font-black uppercase mb-2",
    portalInput: "w-full border-4 border-black p-3 font-mono text-sm focus:outline-none focus:bg-[#FFF9C4] mb-4 bg-white shadow-[4px_4px_0_0_#000] text-black",
    portalBtnSearch: "w-full bg-[#00E5FF] hover:bg-[#00CBE5] text-black font-black uppercase text-sm p-3 border-4 border-black shadow-[6px_6px_0_0_#000] active:translate-x-1 active:translate-y-1 active:shadow-none transition-all disabled:opacity-50",
    portalMsg: "mt-6 p-3 border-4 border-black bg-black text-white font-bold text-[10px] uppercase",
    
    portalCol2: "md:col-span-2 bg-white border-4 border-black shadow-[8px_8px_0_0_#000] p-6 md:p-8 text-black",
    portalCol2Title: "text-2xl font-black uppercase mb-6 border-b-4 border-black pb-2",
    portalEmpty: "border-4 border-dashed border-neutral-300 p-12 flex flex-col items-center justify-center text-neutral-400 font-black uppercase text-sm",
    
    statePendingBox: "bg-[#FF6B00] border-4 border-black p-6 text-black shadow-[6px_6px_0_0_#000] animate-pulse",
    statePendingTitle: "font-black uppercase text-lg",
    statePendingText: "text-xs font-bold",
    statePendingBtn: "w-full bg-black text-[#FF6B00] hover:text-white font-black uppercase p-3 border-2 border-black transition-colors mt-4",
    
    stateOkBox: "bg-[#F4F4F7] border-8 border-double border-black p-6 relative mt-6",
    stateOkSeal: "absolute -top-6 -right-2 md:-right-6 bg-[#00FF66] border-4 border-black p-3 shadow-[4px_4px_0_0_#000] transform rotate-12 font-black uppercase text-xs md:text-sm text-black",
    stateOkTitle: "font-black uppercase text-xl border-b-2 border-black pb-2 mb-4",
    stateOkGrid: "grid grid-cols-2 gap-4 text-sm font-bold",
    stateOkLabel: "block text-[10px] text-neutral-500 uppercase",
    stateOkValue: "text-lg font-black",
    
    stateRevokedBox: "bg-[#FF0055] border-4 border-black p-6 text-white shadow-[6px_6px_0_0_#000]",
    stateRevokedTitle: "font-black uppercase text-xl mb-2",
    stateRevokedReasonBox: "bg-black p-3 font-mono text-sm border-2 border-black mt-2",
    
    hashBox: "bg-neutral-200 border-4 border-black p-4 text-xs font-bold break-all mt-6",
    hashBoxLabel: "text-[10px] uppercase text-neutral-600 block mb-1",

    // Verificador
    verHeaderBox: "text-center mb-12",
    verTitle: "text-4xl md:text-5xl font-black uppercase mb-4 tracking-tighter",
    verSubtitle: "font-bold text-sm bg-black text-white inline-block px-4 py-1 border-2 border-black rotate-1 mt-2",
    verCard: "bg-white border-4 border-black p-8 shadow-[8px_8px_0_0_#000] text-black",
    verInputLabel: "block text-xs font-black uppercase mb-2",
    verInput: "w-full border-4 border-black p-3 font-mono text-sm focus:outline-none focus:bg-[#FFF9C4] mb-4 bg-white shadow-[4px_4px_0_0_#000] text-black",
    verBtn: "w-full bg-[#00E5FF] hover:bg-[#00CBE5] text-black font-black uppercase text-sm p-3 border-4 border-black shadow-[4px_4px_0_0_#000] active:translate-x-1 active:translate-y-1 active:shadow-none transition-all disabled:opacity-50",
    verDrop: "relative border-4 border-dashed border-black bg-neutral-50 hover:bg-[#FFF9C4] transition-colors p-8 text-center cursor-pointer active:translate-y-1 shadow-[4px_4px_0_0_#000] group",
    verDropTitle: "font-black uppercase text-sm",
    verDropText: "text-[10px] font-bold text-neutral-500 mt-2",
    
    verErrorBox: "bg-[#FF0055] border-4 border-black p-6 text-white shadow-[8px_8px_0_0_#000] flex flex-col md:flex-row items-center gap-6 animate-pulse mt-8",
    verErrorIcon: "text-6xl bg-white rounded-full p-2 border-4 border-black text-center",
    verErrorTitle: "text-2xl font-black uppercase mb-1",
    verErrorText: "font-bold text-sm bg-black text-[#FF0055] p-2 border-2 border-white",

    verOkBox: "bg-[#FFE600] border-4 border-black p-8 shadow-[12px_12px_0_0_#000] transform -rotate-1 mt-8 text-black",
    verOkHeader: "flex justify-between items-start mb-6 border-b-4 border-black pb-4",
    verOkTitle: "text-3xl font-black uppercase tracking-tight bg-white px-2 border-2 border-black inline-block",
    verOkText: "font-bold text-sm mt-2 bg-black text-white px-2 py-1 inline-block",
    verOkIcon: "bg-black text-[#00FF66] p-3 border-4 border-white shadow-[4px_4px_0_0_#000] transform rotate-12 text-2xl font-black",
    verOkGrid: "grid grid-cols-1 md:grid-cols-2 gap-6 bg-white border-4 border-black p-6 font-bold text-sm shadow-[4px_4px_0_0_#000]",
  },

  neon: {
    name: "🌃 Neon",
    appBg: "bg-transparent selection:bg-[#00FF66] selection:text-black transition-colors duration-300",
    header: "bg-[#0A0A0F] border-b border-[#FF0055] shadow-[0_0_15px_rgba(255,0,85,0.3)] p-4 sticky top-0 z-50",
    headerLogoBg: "bg-black border border-[#00FF66] p-2 text-[#00FF66] shadow-[0_0_10px_rgba(0,255,102,0.5)]",
    headerTitle: "text-2xl font-mono uppercase tracking-widest text-[#00FF66] ml-4",
    headerSubtitle: "text-[10px] font-mono text-[#FF0055] uppercase mt-1 ml-4 tracking-widest",
    btnToggle: "bg-transparent text-[#00E5FF] border border-[#00E5FF] rounded px-3 py-2 text-xs font-mono uppercase shadow-[0_0_10px_rgba(0,229,255,0.3)] hover:bg-[#00E5FF] hover:text-black transition-all",
    btnWallet: "bg-transparent text-[#00FF66] border border-[#00FF66] rounded px-6 py-2 text-sm font-mono uppercase shadow-[0_0_10px_rgba(0,255,102,0.3)] hover:bg-[#00FF66] hover:text-black transition-all",
    btnDisconnect: "bg-transparent text-[#FF0055] border border-[#FF0055] rounded px-3 py-2 text-xs font-mono uppercase shadow-[0_0_10px_rgba(255,0,85,0.3)] hover:bg-[#FF0055] hover:text-black transition-all",
    walletBadge: "bg-black text-[#00FF66] border border-[#00FF66] rounded px-4 py-2 font-mono text-xs shadow-[0_0_10px_rgba(0,255,102,0.2)]",
    errorAlert: "bg-black text-[#FF0055] border border-[#FF0055] rounded p-4 font-mono uppercase text-sm mb-6 shadow-[0_0_15px_rgba(255,0,85,0.3)] animate-pulse",
    
    tabActive: "bg-[#00FF66] text-black rounded font-mono uppercase px-6 py-3 text-sm shadow-[0_0_15px_rgba(0,255,102,0.5)]",
    tabInactive: "bg-transparent text-[#666] border border-[#333] rounded hover:border-[#00E5FF] hover:text-[#00E5FF] hover:shadow-[0_0_15px_rgba(0,229,255,0.2)] font-mono uppercase px-6 py-3 text-sm transition-all",
    
    // Panel Emisor
    panelHeader: "mb-8 bg-[#0A0A0F] border border-[#00E5FF] rounded p-4 shadow-[0_0_15px_rgba(0,229,255,0.2)] flex flex-col md:flex-row justify-between items-center text-[#00E5FF]",
    panelTitle: "text-3xl md:text-4xl font-mono uppercase tracking-widest",
    panelSubtitle: "font-mono text-xs mt-2 uppercase text-[#FF0055]",
    panelRole: "mt-4 md:mt-0 bg-transparent text-[#FF0055] border border-[#FF0055] rounded px-4 py-2 font-mono text-xs shadow-[0_0_10px_rgba(255,0,85,0.2)]",
    
    cardMain: "bg-[#0A0A0F] border border-[#333] rounded-lg shadow-[0_0_20px_rgba(0,255,102,0.05)] p-6 md:p-8 text-[#00FF66] font-mono",
    dropZone: "mb-8 border-2 border-dashed border-[#FF0055] bg-black hover:bg-[#111] transition-colors p-8 rounded-lg flex flex-col items-center justify-center cursor-pointer shadow-[0_0_15px_rgba(255,0,85,0.2)] text-[#FF0055]",
    dropText: "font-mono uppercase text-sm mt-4 text-center",
    dropSubtext: "text-xs font-mono mt-2 opacity-70 text-center",
    
    inputWrapper: "flex flex-col gap-1",
    inputLabelHash: "text-[#00E5FF] text-[10px] font-mono uppercase",
    inputLabelNombre: "text-[#00FF66] text-[10px] font-mono uppercase",
    inputLabelCarrera: "text-[#FF0055] text-[10px] font-mono uppercase",
    inputLabelWallet: "text-[#FFE600] text-[10px] font-mono uppercase",
    inputField: "w-full border border-[#333] rounded p-4 font-mono text-sm focus:outline-none focus:border-[#00E5FF] focus:shadow-[0_0_10px_rgba(0,229,255,0.3)] transition-all bg-black text-[#00FF66]",
    
    btnSubmit: "w-full bg-transparent border border-[#00FF66] text-[#00FF66] hover:bg-[#00FF66] hover:text-black rounded font-mono uppercase text-lg p-4 shadow-[0_0_15px_rgba(0,255,102,0.3)] transition-all mt-6 disabled:opacity-50",
    statusBox: "mt-8 p-4 border border-[#00E5FF] rounded bg-black text-[#00E5FF] font-mono text-sm uppercase shadow-[0_0_15px_rgba(0,229,255,0.2)]",
    
    sidebarCard: "bg-[#0A0A0F] border border-[#333] rounded-lg shadow-[0_0_20px_rgba(255,0,85,0.05)] p-6 h-fit text-[#FF0055] font-mono",
    sidebarHeader: "text-lg font-mono uppercase border-b border-[#333] pb-3 mb-6",
    sidebarItem1: "flex items-center justify-between border border-[#333] rounded p-3 bg-black mb-4 shadow-[0_0_10px_rgba(0,255,102,0.1)]",
    sidebarItem1Label: "text-xs font-mono uppercase text-[#00FF66]",
    sidebarItem1Value: "text-xs font-mono text-[#00FF66]",
    sidebarItem2: "border border-[#333] rounded p-3 bg-black mb-4 text-[#00FF66] shadow-[0_0_10px_rgba(0,255,102,0.1)]",
    sidebarItem2Label: "block text-[10px] font-mono uppercase opacity-70 mb-2 text-[#00FF66]",
    sidebarItem3: "border border-[#333] rounded p-3 bg-black mb-4 text-[#FF0055] shadow-[0_0_10px_rgba(255,0,85,0.1)]",
    sidebarItem3Label: "block text-[10px] font-mono uppercase opacity-70 mb-2 text-[#FF0055]",
    sidebarItem3Value: "text-2xl font-mono text-[#FF0055]",
    sidebarItem4: "border border-[#333] rounded p-3 bg-black text-[#00E5FF] shadow-[0_0_10px_rgba(0,229,255,0.1)]",
    sidebarItem4Label: "block text-[10px] font-mono uppercase opacity-70 mb-2 text-[#00E5FF]",
    
    // Portal Estudiante
    portalHeader: "mb-8 bg-black border border-[#00FF66] rounded p-4 shadow-[0_0_15px_rgba(0,255,102,0.2)] flex flex-col md:flex-row justify-between md:items-center gap-4 text-[#00FF66]",
    portalTitle: "text-3xl font-mono uppercase tracking-widest",
    portalSubtitle: "font-mono text-xs mt-1 uppercase opacity-80 text-[#FF0055]",
    portalWallet: "bg-[#111] text-[#00FF66] px-4 py-2 font-mono text-xs border border-[#00FF66] rounded break-all shadow-[0_0_10px_rgba(0,255,102,0.2)]",
    portalCol1: "bg-[#0A0A0F] border border-[#333] rounded-lg shadow-[0_0_20px_rgba(0,229,255,0.05)] p-6 h-fit text-[#00E5FF] font-mono",
    portalCol1Title: "text-lg font-mono uppercase mb-4 border-b border-[#333] pb-2",
    portalCol1Text: "text-xs opacity-70 mb-4",
    portalInputLabel: "block text-xs font-mono uppercase mb-2",
    portalInput: "w-full border border-[#333] rounded p-3 font-mono text-sm focus:outline-none focus:border-[#00E5FF] focus:shadow-[0_0_10px_rgba(0,229,255,0.3)] mb-4 bg-black text-[#00E5FF]",
    portalBtnSearch: "w-full bg-transparent border border-[#00E5FF] hover:bg-[#00E5FF] hover:text-black text-[#00E5FF] font-mono uppercase text-sm p-3 rounded shadow-[0_0_15px_rgba(0,229,255,0.3)] transition-all disabled:opacity-50",
    portalMsg: "mt-6 p-3 border border-[#FF0055] rounded bg-black text-[#FF0055] font-mono text-xs uppercase shadow-[0_0_10px_rgba(255,0,85,0.2)]",
    
    portalCol2: "md:col-span-2 bg-[#0A0A0F] border border-[#333] rounded-lg shadow-[0_0_20px_rgba(0,255,102,0.05)] p-6 md:p-8 text-[#00FF66] font-mono",
    portalCol2Title: "text-2xl font-mono uppercase mb-6 border-b border-[#333] pb-2",
    portalEmpty: "border-2 border-dashed border-[#333] rounded p-12 flex flex-col items-center justify-center text-[#444] font-mono uppercase text-sm",
    
    statePendingBox: "bg-black border border-[#FF6B00] rounded p-6 text-[#FF6B00] shadow-[0_0_15px_rgba(255,107,0,0.3)] animate-pulse",
    statePendingTitle: "font-mono uppercase text-lg",
    statePendingText: "text-xs mt-2 opacity-80",
    statePendingBtn: "w-full bg-transparent text-[#FF6B00] border border-[#FF6B00] hover:bg-[#FF6B00] hover:text-black rounded font-mono uppercase p-3 transition-colors mt-4 shadow-[0_0_10px_rgba(255,107,0,0.2)]",
    
    stateOkBox: "bg-black border border-[#00FF66] rounded p-6 relative mt-6 shadow-[0_0_20px_rgba(0,255,102,0.2)]",
    stateOkSeal: "absolute -top-4 -right-2 md:-right-4 bg-black border border-[#00FF66] rounded p-2 shadow-[0_0_10px_rgba(0,255,102,0.5)] font-mono uppercase text-xs md:text-sm text-[#00FF66]",
    stateOkTitle: "font-mono uppercase text-xl border-b border-[#333] pb-2 mb-4",
    stateOkGrid: "grid grid-cols-2 gap-4 text-sm",
    stateOkLabel: "block text-[10px] text-[#00FF66] opacity-70 uppercase",
    stateOkValue: "text-lg font-mono",
    
    stateRevokedBox: "bg-black border border-[#FF0055] rounded p-6 text-[#FF0055] shadow-[0_0_20px_rgba(255,0,85,0.3)]",
    stateRevokedTitle: "font-mono uppercase text-xl mb-2",
    stateRevokedReasonBox: "bg-[#111] p-3 font-mono text-sm border border-[#FF0055] rounded mt-2",
    
    hashBox: "bg-black border border-[#333] rounded p-4 text-xs font-mono break-all mt-6 text-[#00E5FF]",
    hashBoxLabel: "text-[10px] uppercase opacity-70 block mb-1",

    // Verificador
    verHeaderBox: "text-center mb-12 text-[#00FF66]",
    verTitle: "text-4xl md:text-5xl font-mono uppercase mb-4 tracking-widest drop-shadow-[0_0_15px_rgba(0,255,102,0.5)]",
    verSubtitle: "font-mono text-sm text-[#FF0055] uppercase mt-2 tracking-widest",
    verCard: "bg-[#0A0A0F] border border-[#333] rounded-lg p-8 shadow-[0_0_20px_rgba(0,229,255,0.05)] text-[#00E5FF]",
    verInputLabel: "block text-xs font-mono uppercase mb-2",
    verInput: "w-full border border-[#333] rounded p-3 font-mono text-sm focus:outline-none focus:border-[#00E5FF] focus:shadow-[0_0_10px_rgba(0,229,255,0.3)] mb-4 bg-black text-[#00E5FF]",
    verBtn: "w-full bg-transparent border border-[#00E5FF] hover:bg-[#00E5FF] hover:text-black text-[#00E5FF] font-mono uppercase text-sm p-3 rounded shadow-[0_0_15px_rgba(0,229,255,0.3)] transition-all disabled:opacity-50",
    verDrop: "relative border-2 border-dashed border-[#FF0055] bg-black hover:bg-[#111] transition-colors p-8 rounded-lg text-center cursor-pointer shadow-[0_0_15px_rgba(255,0,85,0.2)] text-[#FF0055] group",
    verDropTitle: "font-mono uppercase text-sm mt-4",
    verDropText: "text-[10px] font-mono mt-2 opacity-70",
    
    verErrorBox: "bg-black border border-[#FF0055] rounded p-6 text-[#FF0055] shadow-[0_0_20px_rgba(255,0,85,0.3)] flex flex-col md:flex-row items-center gap-6 animate-pulse mt-8",
    verErrorIcon: "text-6xl drop-shadow-[0_0_10px_rgba(255,0,85,0.8)]",
    verErrorTitle: "text-2xl font-mono uppercase mb-1",
    verErrorText: "font-mono text-sm opacity-90",

    verOkBox: "bg-black border border-[#00FF66] rounded p-8 shadow-[0_0_25px_rgba(0,255,102,0.3)] mt-8 text-[#00FF66]",
    verOkHeader: "flex justify-between items-start mb-6 border-b border-[#333] pb-4",
    verOkTitle: "text-3xl font-mono uppercase tracking-widest",
    verOkText: "font-mono text-sm mt-2 opacity-80",
    verOkIcon: "text-4xl drop-shadow-[0_0_10px_rgba(0,255,102,0.8)]",
    verOkGrid: "grid grid-cols-1 md:grid-cols-2 gap-6 bg-[#0A0A0F] border border-[#333] rounded p-6 font-mono text-sm",
  },

  ejecutivo: {
    name: "👔 Ejecutivo",
    appBg: "bg-transparent selection:bg-blue-200 selection:text-blue-900 transition-colors duration-300",
    header: "bg-white border-b border-gray-200 shadow-sm p-4 sticky top-0 z-50",
    headerLogoBg: "bg-blue-600 text-white rounded-lg p-2 shadow-sm",
    headerTitle: "text-xl font-bold tracking-tight text-gray-900 ml-3",
    headerSubtitle: "text-xs font-medium text-gray-500 mt-0.5 ml-3 uppercase",
    btnToggle: "bg-white text-gray-700 border border-gray-300 rounded-lg px-4 py-2 text-sm font-medium shadow-sm hover:bg-gray-50 transition-all",
    btnWallet: "bg-blue-600 hover:bg-blue-700 text-white rounded-lg px-6 py-2 text-sm font-medium shadow-sm transition-all",
    btnDisconnect: "bg-white text-red-600 border border-gray-300 rounded-lg px-4 py-2 text-sm font-medium hover:bg-red-50 transition-all",
    walletBadge: "bg-green-50 text-green-700 border border-green-200 rounded-lg px-4 py-2 font-medium text-sm",
    errorAlert: "bg-red-50 text-red-700 border border-red-200 rounded-xl p-4 font-medium text-sm mb-6 shadow-sm",
    
    tabActive: "bg-blue-600 text-white rounded-lg font-medium px-6 py-3 text-sm shadow-sm",
    tabInactive: "bg-transparent text-gray-600 hover:bg-gray-100 rounded-lg font-medium px-6 py-3 text-sm transition-all",
    
    // Panel Emisor
    panelHeader: "mb-8 bg-white border border-gray-200 rounded-xl p-6 shadow-sm flex flex-col md:flex-row justify-between items-center text-gray-900",
    panelTitle: "text-2xl font-bold tracking-tight",
    panelSubtitle: "font-medium text-sm mt-1 text-gray-500",
    panelRole: "mt-4 md:mt-0 bg-gray-100 text-gray-700 rounded-lg px-4 py-2 font-medium text-xs",
    
    cardMain: "bg-white border border-gray-200 rounded-2xl shadow-lg p-6 md:p-8 text-gray-900 font-sans",
    dropZone: "mb-8 border-2 border-dashed border-gray-300 bg-gray-50 hover:bg-gray-100 transition-colors p-8 rounded-xl flex flex-col items-center justify-center cursor-pointer text-gray-600",
    dropText: "font-semibold text-base mt-4",
    dropSubtext: "text-sm text-gray-500 mt-2",
    
    inputWrapper: "flex flex-col gap-1 mb-2",
    inputLabelHash: "text-sm font-medium text-gray-700",
    inputLabelNombre: "text-sm font-medium text-gray-700",
    inputLabelCarrera: "text-sm font-medium text-gray-700",
    inputLabelWallet: "text-sm font-medium text-gray-700",
    inputField: "w-full border border-gray-300 rounded-lg p-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-shadow bg-white text-gray-900 shadow-sm",
    
    btnSubmit: "w-full bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-medium text-lg p-4 shadow-md hover:shadow-lg transition-all mt-4 disabled:opacity-50",
    statusBox: "mt-6 p-4 border border-blue-100 rounded-xl bg-blue-50 text-blue-800 font-medium text-sm",
    
    sidebarCard: "bg-white border border-gray-200 rounded-2xl shadow-lg p-6 h-fit text-gray-900 font-sans",
    sidebarHeader: "text-lg font-bold border-b border-gray-100 pb-3 mb-6",
    sidebarItem1: "flex items-center justify-between border border-gray-100 rounded-xl p-3 bg-gray-50 mb-4",
    sidebarItem1Label: "text-sm font-medium text-gray-600",
    sidebarItem1Value: "text-sm font-semibold text-green-600",
    sidebarItem2: "border border-gray-100 rounded-xl p-3 bg-gray-50 mb-4 text-gray-900",
    sidebarItem2Label: "block text-xs font-medium text-gray-500 mb-1",
    sidebarItem3: "border border-gray-100 rounded-xl p-3 bg-gray-50 mb-4 text-gray-900",
    sidebarItem3Label: "block text-xs font-medium text-gray-500 mb-1",
    sidebarItem3Value: "text-2xl font-bold text-gray-900",
    sidebarItem4: "border border-gray-100 rounded-xl p-3 bg-gray-50 text-gray-900",
    sidebarItem4Label: "block text-xs font-medium text-gray-500 mb-1",
    
    // Portal Estudiante
    portalHeader: "mb-8 bg-white border border-gray-200 rounded-xl p-6 shadow-sm flex flex-col md:flex-row justify-between md:items-center gap-4 text-gray-900",
    portalTitle: "text-2xl font-bold tracking-tight",
    portalSubtitle: "font-medium text-sm mt-1 text-gray-500",
    portalWallet: "bg-gray-100 text-gray-700 px-4 py-2 font-medium text-sm rounded-lg break-all",
    portalCol1: "bg-white border border-gray-200 rounded-2xl shadow-lg p-6 h-fit text-gray-900 font-sans",
    portalCol1Title: "text-lg font-bold mb-4 border-b border-gray-100 pb-2",
    portalCol1Text: "text-sm text-gray-600 mb-4",
    portalInputLabel: "block text-sm font-medium text-gray-700 mb-2",
    portalInput: "w-full border border-gray-300 rounded-lg p-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 mb-4 bg-white shadow-sm",
    portalBtnSearch: "w-full bg-blue-600 hover:bg-blue-700 text-white font-medium text-sm p-3 rounded-lg shadow-sm transition-all disabled:opacity-50",
    portalMsg: "mt-6 p-3 border border-red-100 rounded-lg bg-red-50 text-red-700 font-medium text-xs",
    
    portalCol2: "md:col-span-2 bg-white border border-gray-200 rounded-2xl shadow-lg p-6 md:p-8 text-gray-900 font-sans",
    portalCol2Title: "text-xl font-bold mb-6 border-b border-gray-100 pb-2",
    portalEmpty: "border-2 border-dashed border-gray-300 rounded-xl p-12 flex flex-col items-center justify-center text-gray-500 font-medium text-sm",
    
    statePendingBox: "bg-orange-50 border border-orange-200 rounded-xl p-6 text-orange-800 shadow-sm",
    statePendingTitle: "font-bold text-lg",
    statePendingText: "text-sm mt-1",
    statePendingBtn: "w-full bg-orange-600 text-white hover:bg-orange-700 rounded-lg font-medium p-3 transition-colors mt-4 shadow-sm",
    
    stateOkBox: "bg-white border border-gray-200 rounded-xl p-6 relative mt-6 shadow-md",
    stateOkSeal: "absolute -top-3 -right-3 bg-green-100 text-green-800 border border-green-200 rounded-full px-3 py-1 text-xs font-bold shadow-sm",
    stateOkTitle: "font-bold text-lg border-b border-gray-100 pb-2 mb-4",
    stateOkGrid: "grid grid-cols-2 gap-4 text-sm",
    stateOkLabel: "block text-xs text-gray-500 font-medium",
    stateOkValue: "text-base font-semibold text-gray-900",
    
    stateRevokedBox: "bg-red-50 border border-red-200 rounded-xl p-6 text-red-800 shadow-sm",
    stateRevokedTitle: "font-bold text-lg mb-2",
    stateRevokedReasonBox: "bg-white p-3 text-sm border border-red-100 rounded-lg mt-2 text-gray-700",
    
    hashBox: "bg-gray-50 border border-gray-200 rounded-lg p-4 text-xs break-all mt-6 text-gray-600",
    hashBoxLabel: "text-xs font-medium text-gray-500 block mb-1",

    // Verificador
    verHeaderBox: "text-center mb-12",
    verTitle: "text-4xl font-bold mb-3 tracking-tight text-gray-900",
    verSubtitle: "font-medium text-sm text-gray-500",
    verCard: "bg-white border border-gray-200 rounded-2xl p-8 shadow-xl text-gray-900 font-sans",
    verInputLabel: "block text-sm font-medium text-gray-700 mb-2",
    verInput: "w-full border border-gray-300 rounded-lg p-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 mb-4 bg-white shadow-sm",
    verBtn: "w-full bg-blue-600 hover:bg-blue-700 text-white font-medium text-sm p-3 rounded-lg shadow-sm transition-all disabled:opacity-50",
    verDrop: "relative border-2 border-dashed border-gray-300 bg-gray-50 hover:bg-gray-100 transition-colors p-8 rounded-xl text-center cursor-pointer text-gray-600 group",
    verDropTitle: "font-semibold text-sm mt-4",
    verDropText: "text-xs font-medium text-gray-500 mt-2",
    
    verErrorBox: "bg-red-50 border border-red-200 rounded-xl p-6 text-red-800 shadow-sm flex flex-col md:flex-row items-center gap-6 mt-8",
    verErrorIcon: "text-4xl",
    verErrorTitle: "text-xl font-bold mb-1",
    verErrorText: "text-sm",

    verOkBox: "bg-white border border-gray-200 rounded-2xl p-8 shadow-xl mt-8 text-gray-900",
    verOkHeader: "flex justify-between items-start mb-6 border-b border-gray-100 pb-4",
    verOkTitle: "text-2xl font-bold tracking-tight",
    verOkText: "text-sm text-gray-500 mt-1",
    verOkIcon: "text-green-500 text-3xl",
    verOkGrid: "grid grid-cols-1 md:grid-cols-2 gap-6 bg-gray-50 border border-gray-100 rounded-xl p-6 text-sm",
  }
};
